name: bass_fishing_ai_clean_start
description: A clean new start for bass fishing AI app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  http: ^0.13.5
  intl: ^0.18.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/android_foreground.png" # 임시 기본값 (Android에서 무시됨)
  image_path_ios: "assets/icon/ios_app_store.png" # iOS 전용 아이콘

  adaptive_icon_background: "#F5F5F5"
  adaptive_icon_foreground: "assets/icon/android_foreground.png"

flutter:
  uses-material-design: true
